version: "3"
services:
  docker-dev:
    container_name: docker-dev
    build: .
    ports:
      # You may want to pass other common web app testing ports through
      - "3000:3000"
    volumes:
      # Delegated mounts. Favors predictability on the container side
      # and slightly better performance
      - ./projects:/root/.sync:delegated
      - ./data/db:/data/db:delegated
