version: "3"
services:
  docker-dev:
    container_name: docker-dev
    build: .
    ports:
      # You may want to pass other common web app testing ports through
      - "3000:3000"
    volumes:
      # Delegated mounts. More performance, less consistency.
      # This isn't production so that's the right tradeoff
      - ./shared:/root/shared:delegated
      - ./data/db:/data/db:delegated
